#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : quazip
Version  : 0.7.6
Release  : 1
URL      : https://github.com/stachenov/quazip/archive/0.7.6.tar.gz
Source0  : https://github.com/stachenov/quazip/archive/0.7.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: quazip-data = %{version}-%{release}
Requires: quazip-lib = %{version}-%{release}
Requires: quazip-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : pkg-config
BuildRequires : zlib-dev

%description
QuaZIP is the C++ wrapper for Gilles Vollant's ZIP/UNZIP package
(AKA Minizip) using Trolltech's Qt library.

%package data
Summary: data components for the quazip package.
Group: Data

%description data
data components for the quazip package.


%package dev
Summary: dev components for the quazip package.
Group: Development
Requires: quazip-lib = %{version}-%{release}
Requires: quazip-data = %{version}-%{release}
Provides: quazip-devel = %{version}-%{release}

%description dev
dev components for the quazip package.


%package lib
Summary: lib components for the quazip package.
Group: Libraries
Requires: quazip-data = %{version}-%{release}
Requires: quazip-license = %{version}-%{release}

%description lib
lib components for the quazip package.


%package license
Summary: license components for the quazip package.
Group: Default

%description license
license components for the quazip package.


%prep
%setup -q -n quazip-0.7.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553117710
mkdir -p clr-build
pushd clr-build
export LDFLAGS="${LDFLAGS} -fno-lto"
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1553117710
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/quazip
cp COPYING %{buildroot}/usr/share/package-licenses/quazip/COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake-3.14/Modules/FindQuaZip5.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/quazip5/JlCompress.h
/usr/include/quazip5/ioapi.h
/usr/include/quazip5/minizip_crypt.h
/usr/include/quazip5/quaadler32.h
/usr/include/quazip5/quachecksum32.h
/usr/include/quazip5/quacrc32.h
/usr/include/quazip5/quagzipfile.h
/usr/include/quazip5/quaziodevice.h
/usr/include/quazip5/quazip.h
/usr/include/quazip5/quazip_global.h
/usr/include/quazip5/quazipdir.h
/usr/include/quazip5/quazipfile.h
/usr/include/quazip5/quazipfileinfo.h
/usr/include/quazip5/quazipnewinfo.h
/usr/include/quazip5/unzip.h
/usr/include/quazip5/zip.h
/usr/lib64/libquazip5.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libquazip5.so.1
/usr/lib64/libquazip5.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/quazip/COPYING
